force-app/main/default/objects/Defect_Report__c/Defect_Report__c.object-meta.xml
<CustomObject>
    <label>Defect Report</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Defect Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defect Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Defect_Report__c/fields/Defect_Area__c.field-meta.xml
<CustomField>
    <fullName>Defect_Area__c</fullName>
    <label>Defect Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MotherBoard</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
            <value>
                <fullName>TouchPad</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Camera</fullName>
            </value>
            <value>
                <fullName>Sound</fullName>
            </value>
            <value>
                <fullName>Connection</fullName>
            </value>
            <value>
                <fullName>Performence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Technician__c.field-meta.xml
<CustomField>
    <fullName>Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>Defect Reports</relationshipLabel>
    <relationshipName>Defect_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Technician__c/Technician__c.object-meta.xml
<CustomObject>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technician__c/fields/Skil_Level__c.field-meta.xml
<CustomField>
    <fullName>Skil_Level__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warranty Specialist</fullName>
            </value>
            <value>
                <fullName>MotherBoard</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Sound</fullName>
            </value>
            <value>
                <fullName>Camera</fullName>
            </value>
            <value>
                <fullName>Performence</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Connection</fullName>
            </value>
            <value>
                <fullName>TouchPad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Defect_ReportHandler.cls
public class Defect_ReportHandler {
   @AuraEnabled(cacheable = true)
    public static void assignTechnicianByDefectArea(List<Defect_Report__c> reports)
    {
        System.debug('defect report==========' + reports);
        String defectedItem;
        String defectReportId; 
        for(Defect_Report__c dr: reports)
        {
           defectedItem = dr.Defect_Area__c ;
           defectReportId = dr.Id;
           if(defectedItem != null && defectReportId != null)
           {
            List<Technician__c> allTechs = [SELECT Id, Name, Skil_Level__c FROM Technician__c WHERE Skil_Level__c =: defectedItem];
            System.debug('all technicians==========' + allTechs); 
               if(!allTechs.isEmpty())
                {
                  Defect_Report__c dre = [SELECT Id,Technician__c FROM Defect_Report__c WHERE Id =: defectReportId LIMIT 1];
                  System.debug('defect report==========' + dre);
                if(dre != null)
                 {
                dre.Technician__c = allTechs[0].Id;
                System.debug('updated defect report==========' + dre);
                update dre;
                 }else{
                      System.debug(' no defect report==========' );
                 }
                }else{
                     System.debug(' no technicians there for this defect==========');
                }
           }
            else{
                 System.debug(' no defect report created ==========');
            }
        }
        
    }
}