force-app/main/default/objects/Defect_Report__c/Defect_Report__c.object-meta.xml
<CustomObject>
    <label>Defect Report</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Defect Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defect Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Defect_Report__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Defect Reports</relationshipLabel>
    <relationshipName>Defect_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Defect_Area__c.field-meta.xml
<CustomField>
    <fullName>Defect_Area__c</fullName>
    <label>Defect Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MotherBoard</fullName>
            </value>
            <value>
                <fullName>CPU</fullName>
            </value>
            <value>
                <fullName>TouchPad</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Camera</fullName>
            </value>
            <value>
                <fullName>Sound</fullName>
            </value>
            <value>
                <fullName>Connection</fullName>
            </value>
            <value>
                <fullName>Performence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Defect_Description__c.field-meta.xml
<CustomField>
    <fullName>Defect_Description__c</fullName>
    <label>Defect Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Defect_Severity__c.field-meta.xml
<CustomField>
    <fullName>Defect_Severity__c</fullName>
    <label>Defect Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Laptop__c.field-meta.xml
<CustomField>
    <fullName>Laptop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Laptop</label>
    <referenceTo>Laptop__c</referenceTo>
    <relationshipLabel>Defect Reports</relationshipLabel>
    <relationshipName>Defect_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defect_Report__c/fields/Reported_Date__c.field-meta.xml
<CustomField>
    <fullName>Reported_Date__c</fullName>
    <label>Reported Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Laptop__c/Laptop__c.object-meta.xml
<CustomObject>
    <label>Laptop</label>
    <nameField>
        <label>Laptop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Laptops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DefectReportHandler.cls
public with sharing class DefectReportHandler {
    @AuraEnabled(cacheable = true)
    public static List<Contact> getAllContacts()
    {
     return [SELECT Id, LastName, Name FROM Contact];
    }
    @AuraEnabled
    public static string createDefectReport(Map<String, Object> defectReportData){
     System.debug('defect report data------->'+ defectReportData);
         String laptop;
         String selectedContact = (string)defectReportData.get('contact');
         if(selectedContact != null)
         {
            Contact con = [SELECT Id, Name , Laptop__c FROM Contact WHERE Id =: selectedContact LIMIT 1];
            System.debug('selected contact------->'+ con);
            if(con.Laptop__c != null)
            {
                System.debug('old laptop Id------->'+ con.Laptop__c);
                laptop = con.Laptop__c;
                Defect_Report__c dr = new Defect_Report__c();
                dr.Customer_Contact__c = selectedContact;
                dr.Defect_Area__c = (string)defectReportData.get('defectArea');
                dr.Defect_Description__c = (string)defectReportData.get('defectDescription');
                dr.Defect_Severity__c = (string)defectReportData.get('defectSeverity');
                String reportedDate = (string)defectReportData.get('reportedDate');
                if(reportedDate != null)
                {
                    dr.Reported_Date__c = date.valueOf(reportedDate);
                }
                dr.Laptop__c = con.Laptop__c;
                System.debug('new defect report data------>'+ dr);
                insert dr;
                 return dr.Id;
            }else{
              return  'defect report not created';
            }
           
         }else{
            return 'contact is not avialable';
         }
    }
 }