force-app/main/default/objects/Laptop__c/Laptop__c.object-meta.xml
<CustomObject>
    <label>Laptop</label>
    <nameField>
        <label>Laptop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Laptops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Laptop__c/fields/Laptop_Model__c.field-meta.xml
<CustomField>
    <fullName>Laptop_Model__c</fullName>
    <label>Laptop Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Laptop__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Laptops</relationshipLabel>
    <relationshipName>Laptops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Laptop__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Use</fullName>
            </value>
            <value>
                <fullName>Defective</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Laptop__c/fields/Warranty_ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>Warranty_ExpirationDate__c</fullName>
    <label>Warranty ExpirationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Order_Cost__c.field-meta.xml
<CustomField>
    <fullName>Order_Cost__c</fullName>
    <label>Order Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Order_ModelName__c.field-meta.xml
<CustomField>
    <fullName>Order_ModelName__c</fullName>
    <label>Order ModelName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LaptopDetailsHandler.cls
public with sharing class LaptopDetailsHandler {
   @AuraEnabled(cacheable = true)
   public static List<Purchase_Order__c> getAllPurchaseOrders(){
    try {
        List<Purchase_Order__c> orders = [SELECT Id, Name, Vendor__c, Total_Quantity__c, Order_Status__c, Order_ModelName__c, Order_Date__c, Order_Cost__c FROM Purchase_Order__c];
        if(! orders.isEmpty())
        {
             return orders;
        }
        else{
            return null;
        }
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
   @AuraEnabled
   public static string createLaptopDetails(Map<string, Object> laptopData){
    try {
        System.debug('laptop data from java script' + laptopData);
        Laptop__c lap = new Laptop__c();
        lap.Name = (string)laptopData.get('name');
        lap.Status__c = (string)laptopData.get('status');
        lap.Location__c = (string)laptopData.get('location');
        lap.Laptop_Model__c = (string)laptopData.get('model');
        String purchaseDate = (String)laptopData.get('purchaseDate');
        if(purchaseDate != null)
        {
            lap.Purchase_Date__c = date.valueOf(purchaseDate);
        }
        String warrantyExpireData = (String)laptopData.get('warrantyExpirationDate');
        if(warrantyExpireData != null)
        {
            lap.Warranty_ExpirationDate__c = date.valueOf(warrantyExpireData);
        }
        lap.Purchase_Order__c =(Id)laptopData.get('purchaseOrder');

        insert lap;

        System.debug('laptop data in apex' + lap);
        return lap.Id;
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }
}